libuavcan: libuavcan::duration::Base< Type, USecT > Class Template Reference
libuavcan::duration::Base< Type, USecT > Class Template Reference
#include "libuavcan/time.hpp"
Public Types
using MicrosecondType = USecT
using DurationType = Type
Public Member Functions
USecT toMicrosecond () const
Type getAbs () const
Static Public Member Functions
static Type getMaximum ()
static Type fromMicrosecond (USecT us)
Protected Member Functions
~Base ()=default
Base (Base &&rhs)
Detailed Description
template<typename Type, typename USecT = libuavcan::DefaultMicrosecondSignedType>
class libuavcan::duration::Base< Type, USecT >
Protected base class for duration values. This provides a common implementation for various duration datatypes and enforces two concepts:
duration math is saturing – MAX_DURATION + 1 == MAX_DURATION
durations are signed integers – By default 8 byte integers but USecT can be redefined by a specialization.
Template Parameters
Type The type of the derived class. This must be an empty type. All storage will be provided by this base class.
USecT The datatype returned when retrieving durations from realizations of this base class. This type must be signed.
Member Typedef Documentation
DurationType
template<typename Type, typename USecT = libuavcan::DefaultMicrosecondSignedType> using libuavcan::duration::Base< Type, USecT >::DurationType = Type
The specialized type of this base duration type.
MicrosecondType
template<typename Type, typename USecT = libuavcan::DefaultMicrosecondSignedType> using libuavcan::duration::Base< Type, USecT >::MicrosecondType = USecT
The underlying datatype for microsecond values. This must be signed for duration types.
Constructor & Destructor Documentation
~Base()
template<typename Type, typename USecT = libuavcan::DefaultMicrosecondSignedType> libuavcan::duration::Base< Type, USecT >::~Base () protected default
Non-virtual destructor.
Base()
template<typename Type, typename USecT = libuavcan::DefaultMicrosecondSignedType> libuavcan::duration::Base< Type, USecT >::Base (Base< Type, USecT > && rhs) inline protected
Move constructor takes value from rhs and resets rhs to 0.
Member Function Documentation
fromMicrosecond()
template<typename Type, typename USecT = libuavcan::DefaultMicrosecondSignedType> static Type libuavcan::duration::Base< Type, USecT >::fromMicrosecond (USecT us) inline static
Construct an instance of Type from a microsecond value.
Referenced by libuavcan::duration::Base< Monotonic >::getAbs(), libuavcan::duration::Base< Monotonic >::getMaximum(), libuavcan::time::Base< Monotonic, duration::Monotonic >::getMaximum(), and libuavcan::time::Base< Monotonic, duration::Monotonic >::toMicrosecond().
getAbs()
template<typename Type, typename USecT = libuavcan::DefaultMicrosecondSignedType> Type libuavcan::duration::Base< Type, USecT >::getAbs () const inline
Get the absolute value of the duration as a duration type.
getMaximum()
template<typename Type, typename USecT = libuavcan::DefaultMicrosecondSignedType> static Type libuavcan::duration::Base< Type, USecT >::getMaximum () inline static
Get the largest possible number of microseconds this type can store.
toMicrosecond()
template<typename Type, typename USecT = libuavcan::DefaultMicrosecondSignedType> USecT libuavcan::duration::Base< Type, USecT >::toMicrosecond () const inline
Obtain the underlying microsecond value without conversion.
The documentation for this class was generated from the following file:
libuavcan/include/libuavcan/time.hpp
UAVCAN – Copyright (C) 2014-1029 Pavel Kirienko – Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved – This documentation is provided under the MIT licence as part of the libuavcan project.