libuavcan: libuavcan::example::SocketCANInterface Class Reference
libuavcan::example::SocketCANInterface Class Reference final
#include "/repo/test/linux/example/media_on_linux/SocketCANInterface.hpp"
Public Member Functions
const std::string & getInterfaceName () const
void getStatistics (Statistics &out_stats) const
int getSocketDescriptor () const
std::uint_fast8_t getInterfaceIndex () const
libuavcan::Result write (const FrameType(&frame)[TxFramesLen], std::size_t frames_len, std::size_t &out_frames_written)
libuavcan::Result read (FrameType(&out_frames)[RxFramesLen], std::size_t &out_frames_read)
Detailed Description
Example of a media::Interface implemented for SocketCAN.
Member Function Documentation
getInterfaceIndex()
std::uint_fast8_t libuavcan::example::SocketCANInterface::getInterfaceIndex () const
Return the index for this interface. This is a zero based non-sparse range used by methods on the libuavcan::media::InterfaceGroup interface.
Note that this is not related to the posix socket interface index.
Returns
This interface's index.
getInterfaceName()
const std::string & libuavcan::example::SocketCANInterface::getInterfaceName () const
Get the name used to bind to the interface.
getSocketDescriptor()
int libuavcan::example::SocketCANInterface::getSocketDescriptor () const
Get the underlying file descriptor this object encapsulates.
getStatistics()
void libuavcan::example::SocketCANInterface::getStatistics (Statistics & out_stats) const
Get the current statistics for this interface.
read()
libuavcan::Result libuavcan::example::SocketCANInterface::read (FrameType(&) out_frames[RxFramesLen], std::size_t & out_frames_read)
See libuavcan::media::InterfaceGroup::read for documentation.
References libuavcan::time::Base< Monotonic, duration::Monotonic >::fromMicrosecond(), libuavcan::SuccessNothing, and libuavcan::UnknownInternalError.
write()
libuavcan::Result libuavcan::example::SocketCANInterface::write (const FrameType(&) frame[TxFramesLen], std::size_t frames_len, std::size_t & out_frames_written)
See libuavcan::media::InterfaceGroup::write for documentation.
References libuavcan::BadArgument, libuavcan::BufferFull, libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::data, libuavcan::Failure, libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::getDataLength(), libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::getDLC(), libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::id, libuavcan::Success, and libuavcan::SuccessPartial.
The documentation for this class was generated from the following files:
linux/example/media_on_linux/SocketCANInterface.hpp
linux/example/media_on_linux/SocketCANInterface.cpp
UAVCAN – Copyright (C) 2014-1029 Pavel Kirienko – Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved – This documentation is provided under the MIT licence as part of the libuavcan project.