libuavcan: libuavcan/include/libuavcan/util/math.hpp File Reference
math.hpp File Reference
#include "libuavcan/libuavcan.hpp"
#include <cstdlib>
#include <cmath>
#include "libuavcan/introspection.hpp"
Namespaces
libuavcan
util
Functions
template<class SignedType , typename std::enable_if< std::is_integral< SignedType >::value &&std::is_signed< SignedType >::value, int >::type = 0>
SignedType libuavcan::util::saturating_add (SignedType left, SignedType right)
template<class SignedType , typename std::enable_if< std::is_integral< SignedType >::value &&std::is_signed< SignedType >::value, int >::type = 0>
SignedType libuavcan::util::saturating_sub (SignedType left, SignedType right)
template<class UnsignedType , typename std::enable_if< std::is_integral< UnsignedType >::value &&!std::is_signed< UnsignedType >::value, int >::type = 0>
constexpr UnsignedType libuavcan::util::saturating_add (UnsignedType left, UnsignedType right)
template<class UnsignedType , typename std::enable_if< std::is_integral< UnsignedType >::value &&!std::is_signed< UnsignedType >::value, int >::type = 0>
constexpr UnsignedType libuavcan::util::saturating_sub (UnsignedType left, UnsignedType right)
template<class LhsType , class RhsType , typename std::enable_if< std::is_integral< LhsType >::value &&!std::is_signed< LhsType >::value &&std::is_integral< RhsType >::value &&std::is_signed< RhsType >::value, int >::type = 0>
constexpr LhsType libuavcan::util::saturating_sub (LhsType left, RhsType right)
template<class LhsType , class RhsType , typename std::enable_if< std::is_integral< LhsType >::value &&!std::is_signed< LhsType >::value &&std::is_integral< RhsType >::value &&std::is_signed< RhsType >::value, int >::type = 0>
constexpr LhsType libuavcan::util::saturating_add (LhsType left, RhsType right)
Function Documentation
saturating_add() [1/3]
template<class SignedType , typename std::enable_if< std::is_integral< SignedType >::value &&std::is_signed< SignedType >::value, int >::type = 0> SignedType libuavcan::util::saturating_add (SignedType left, SignedType right)
Generic implementation of a saturating add operation that does not require integer promotion (i.e. will work with int64_t without needing a 128-bit type). This is very branchy code so we should provide implementations that use hardware support for saturation arithmetic.
Template Parameters
SignedType The signed integer type of both operands.
0 For SFINAE
Parameters
left The left operand.
right The right operand.
Returns
SignedType The result which will saturate to
std::numeric_limits<SignedType>::min()
or
std::numeric_limits<SignedType>::max()
References libuavcan::util::saturating_add().
Referenced by libuavcan::util::saturating_add().
saturating_add() [2/3]
template<class UnsignedType , typename std::enable_if< std::is_integral< UnsignedType >::value &&!std::is_signed< UnsignedType >::value, int >::type = 0> constexpr UnsignedType libuavcan::util::saturating_add (UnsignedType left, UnsignedType right)
Generic implementation of a saturating add operation that does not require integer promotion (i.e. will work with int64_t without needing a 128-bit type). This is very branchy code so we should provide implementations that use hardware support for saturation arithmetic.
Template Parameters
UnsignedType The unsigned integer type of both operands.
0 For SFINAE
Parameters
left The left operand.
right The right operand.
Returns
UnsignedType The result which will saturate to
std::numeric_limits<UnsignedType>::min()
or
std::numeric_limits<UnsignedType>::max()
References libuavcan::util::saturating_add().
saturating_add() [3/3]
template<class LhsType , class RhsType , typename std::enable_if< std::is_integral< LhsType >::value &&!std::is_signed< LhsType >::value &&std::is_integral< RhsType >::value &&std::is_signed< RhsType >::value, int >::type = 0> constexpr LhsType libuavcan::util::saturating_add (LhsType left, RhsType right)
Generic implementation of a saturating subtraction operation that does not require integer promotion (i.e. will work with int64_t without needing a 128-bit type). This is very branchy code so we should provide implementations that use hardware support for saturation arithmetic.
This version allows a saturated addition of a signed integer with an unsigned.
Template Parameters
LHS_TYPE The unsigned integer type of the left-hand-side operand.
RHS_TYPE The signed integer type of the right-hand-side operand.
0 For SFINAE
Parameters
left The signed left operand.
right The unsigned right operand.
Returns
LHS_TYPE The result which will saturate to
std::numeric_limits<LHS_TYPE>::min()
or
std::numeric_limits<LHS_TYPE>::max()
References libuavcan::util::saturating_add().
saturating_sub() [1/3]
template<class SignedType , typename std::enable_if< std::is_integral< SignedType >::value &&std::is_signed< SignedType >::value, int >::type = 0> SignedType libuavcan::util::saturating_sub (SignedType left, SignedType right)
Generic implementation of a saturating subtract operation that does not require integer promotion (i.e. will work with int64_t without needing a 128-bit type). This is very branchy code so we should provide implementations that use hardware support for saturation arithmetic.
Template Parameters
SignedType The signed integer type of both operands.
0 For SFINAE
Parameters
left The left operand.
right The right operand.
Returns
SignedType The result which will saturate to
std::numeric_limits<SignedType>::min()
or
std::numeric_limits<SignedType>::max()
References libuavcan::util::saturating_sub().
Referenced by libuavcan::util::saturating_sub().
saturating_sub() [2/3]
template<class UnsignedType , typename std::enable_if< std::is_integral< UnsignedType >::value &&!std::is_signed< UnsignedType >::value, int >::type = 0> constexpr UnsignedType libuavcan::util::saturating_sub (UnsignedType left, UnsignedType right)
Generic implementation of a saturating subtraction operation that does not require integer promotion (i.e. will work with int64_t without needing a 128-bit type). This is very branchy code so we should provide implementations that use hardware support for saturation arithmetic.
Template Parameters
UnsignedType The unsigned integer type of both operands.
0 For SFINAE
Parameters
left The left operand.
right The right operand.
Returns
UnsignedType The result which will saturate to
std::numeric_limits<UnsignedType>::min()
or
std::numeric_limits<UnsignedType>::max()
References libuavcan::util::saturating_sub().
saturating_sub() [3/3]
template<class LhsType , class RhsType , typename std::enable_if< std::is_integral< LhsType >::value &&!std::is_signed< LhsType >::value &&std::is_integral< RhsType >::value &&std::is_signed< RhsType >::value, int >::type = 0> constexpr LhsType libuavcan::util::saturating_sub (LhsType left, RhsType right)
Generic implementation of a saturating subtraction operation that does not require integer promotion (i.e. will work with int64_t without needing a 128-bit type). This is very branchy code so we should provide implementations that use hardware support for saturation arithmetic.
This version allows a saturated subtraction of a signed integer from an unsigned.
Template Parameters
LHS_TYPE The unsigned integer type of the left-hand-side operand.
RHS_TYPE The signed integer type of the right-hand-side operand.
0 For SFINAE
Parameters
left The signed left operand.
right The unsigned right operand.
Returns
LHS_TYPE The result which will saturate to
std::numeric_limits<LHS_TYPE>::min()
or
std::numeric_limits<LHS_TYPE>::max()
References libuavcan::util::saturating_sub().
UAVCAN – Copyright (C) 2014-1029 Pavel Kirienko – Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved – This documentation is provided under the MIT licence as part of the libuavcan project.