libuavcan: /repo/libuavcan_validation_suite/include/lvs/platform/memory_copy.hpp File Reference
memory_copy.hpp File Reference
#include "lvs/lvs.hpp"
#include "libuavcan/platform/memory.hpp"
Namespaces
lvs
Functions
lvs::platform::memory::TEST (CopyBitsTest, InputsValidation)
lvs::platform::memory::TEST (CopyBitsTest, OneByteAlignedIntoOneAligned)
lvs::platform::memory::TEST (CopyBitsTest, OneByteAlignedIntoOneUnaligned)
lvs::platform::memory::TEST (CopyBitsTest, OneByteUnalignedIntoOneAligned)
lvs::platform::memory::TEST (CopyBitsTest, TwoBitsUnalignedIntoAligned)
lvs::platform::memory::TEST (CopyBitsTest, TwoBitsAlignedIntoUnaligned)
lvs::platform::memory::TEST (CopyBitsTest, TwoByteAlignedIntoTwoAligned)
lvs::platform::memory::TEST (CopyBitsTest, TwoByteUnalignedIntoTwoAligned)
lvs::platform::memory::TEST (CopyBitsTest, TwoByteAlignedIntoTwoUnaligned)
lvs::platform::memory::TEST (CopyBitsTest, StringUnalignedIntoStringAligned)
lvs::platform::memory::TEST (CopyBitsTest, SrcOffsetIsGreaterThanEight)
lvs::platform::memory::TEST (CopyBitsTest, DstOffsetIsGreaterThanEight)
Detailed Description
Include this test in a google test application to verify unaligned bit copy for your platform.
Function Documentation
TEST() [1/12]
lvs::platform::memory::TEST (CopyBitsTest , InputsValidation)
Cover all mundane cases where inputs are out of range or invalid.
References lvs::platform::memory::TEST().
Referenced by lvs::platform::memory::TEST().
TEST() [2/12]
lvs::platform::memory::TEST (CopyBitsTest , OneByteAlignedIntoOneAligned)
Copy from one byte aligned into another aligned.
References lvs::platform::memory::TEST().
TEST() [3/12]
lvs::platform::memory::TEST (CopyBitsTest , OneByteAlignedIntoOneUnaligned)
Copy from one byte aligned into another unaligned.
dst (iit)    = 11111111
src          = 01010101
dst (result) = 10101011
dst (iit)    = 00000000
src          = 01010101
dst (result) = 10101010
References lvs::platform::memory::TEST().
TEST() [4/12]
lvs::platform::memory::TEST (CopyBitsTest , OneByteUnalignedIntoOneAligned)
Copy from one byte unaligned into another aligned.
dst (init)   = 11111111
src          = 01010101
dst (result) = 10101010
dst (init)   = 00000000
src          = 01010101
dst (result) = 10101010
References lvs::platform::memory::TEST().
TEST() [5/12]
lvs::platform::memory::TEST (CopyBitsTest , TwoBitsUnalignedIntoAligned)
Copy just two bits from an unaligned source.
dst (init)   = 10000000
src          = 11111111
dst (result) = 10000011
References lvs::platform::memory::TEST().
TEST() [6/12]
lvs::platform::memory::TEST (CopyBitsTest , TwoBitsAlignedIntoUnaligned)
Copy just two bits to an unaligned destination.
dst (init)   = 00000001
src          = 11111111
dst (result) = 11000001
References lvs::platform::memory::TEST().
TEST() [7/12]
lvs::platform::memory::TEST (CopyBitsTest , TwoByteAlignedIntoTwoAligned)
Copy from two integers aligned into two aligned.
References lvs::platform::memory::TEST().
TEST() [8/12]
lvs::platform::memory::TEST (CopyBitsTest , TwoByteUnalignedIntoTwoAligned)
Copy from two integers unaligned into two aligned.
dst (init)   = 11111111 11111111
src          = 01010101 01010101
dst (result) = 10101010 10101010
dst (init)   = 00000000 00000000
src          = 01010101 01010101
dst (result) = 00101010 10101010
References lvs::platform::memory::TEST().
TEST() [9/12]
lvs::platform::memory::TEST (CopyBitsTest , TwoByteAlignedIntoTwoUnaligned)
Copy from two integers aligned into two unaligned. dst (init) = 11111111 11111111 src = 10101010 10101010 dst (result) = 01010101 01010101
dst (init) = 00000000 00000000 src = 10101010 10101010 dst (result) = 01010101 01010100
References lvs::platform::memory::TEST().
TEST() [10/12]
lvs::platform::memory::TEST (CopyBitsTest , StringUnalignedIntoStringAligned)
Sanity check that I'm not confused. Bits can be hard to reason about but words either make sense or don't.
References lvs::platform::memory::TEST().
TEST() [11/12]
lvs::platform::memory::TEST (CopyBitsTest , SrcOffsetIsGreaterThanEight)
Unaligned to aligned where the offset is greater than one byte. dst (init) = 11111111 11111111 src = 01010101 01010101 dst (result) = 11111111 10101010
dst (init) = 00000000 00000000 src = 01010101 01010101 dst (result) = 00000000 00101010
References lvs::platform::memory::TEST().
TEST() [12/12]
lvs::platform::memory::TEST (CopyBitsTest , DstOffsetIsGreaterThanEight)
Aligned to unaligned where the offset is greater than one byte. dst (init) = 11111111 11111111 src = 01010101 01010101 dst (result) = 11111111 10101011
dst (init) = 00000000 00000000 src = 01010101 01010101 dst (result) = 00000000 10101010
References lvs::platform::memory::TEST().
UAVCAN – Copyright (C) 2014-1029 Pavel Kirienko – Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved – This documentation is provided under the MIT licence as part of the libuavcan project.