libuavcan: libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask > Struct Template Reference
libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask > Struct Template Reference
#include "libuavcan/media/can.hpp"
Data Structures
struct Filter
Public Member Functions
Frame (const Frame &rhs)
Frame (std::uint32_t can_id, const std::uint8_t *can_data, FrameDLC in_dlc, libuavcan::time::Monotonic can_timestamp)
Frame (std::uint32_t can_id, const std::uint8_t *can_data, FrameDLC in_dlc)
FrameDLC getDLC () const
void setDataLength (std::uint_fast8_t data_length)
std::uint_fast8_t getDataLength () const
bool operator!= (const Frame &rhs) const
bool operator== (const Frame &rhs) const
bool operator< (const Frame &other) const
bool operator> (const Frame &other) const
Frame & operator= (const Frame &rhs)
bool priorityHigherThan (const Frame &rhs) const
bool priorityLowerThan (const Frame &rhs) const
Static Public Member Functions
static FrameDLC lengthToDlc (std::uint_fast8_t length)
static std::uint_fast8_t dlcToLength (FrameDLC dlc)
Data Fields
std::uint32_t id
std::uint8_t data [MTUBytesParam]
libuavcan::time::Monotonic timestamp
Static Public Attributes
static constexpr std::uint32_t MaskExtID = 0x1FFFFFFFU
static constexpr std::uint32_t MaskIdWithFlags
static constexpr std::uint16_t MTUBytes = MTUBytesParam
Detailed Description
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00>
struct libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >
A raw CAN frame, as passed to/from a CAN peripheral or subsystem. This is the datastructure used by the media layer of libuavcan to buffer incoming data that is "interesting" before the transport layer parses it into the high-level types defined by DSDL. Interesting data is defined as CAN frames that are compatible with the UAVCAN protocol. For CAN bus, this omits error frames, remote frames, and any frame using 11-bit identifiers. Such uninteresting frames are not compatible with UAVCAN and it is undefined behaviour to attempt to load such data into a Frame instance.
For systems which consume unsupported CAN frames it is recommended that another data path is established that does not involve libuavcan. For example, a "statistics" interface might be supported by a driver on a system to handle bus error rate at an application level.
Template Parameters
MTUBytesParam The maximum number of bytes that can be stored in this frame.
FlagBitsCompareMask A mask of the upper thee bits of this class's id field. By default these bits are ignored by equality operators in the class. If an implemenation wants to use these three bits as meta-data it should provide a different compare mask to include the bits when comparing identifiers.
Data Domains and Filtering
Libuavcan will introduce two copies of data received on a CAN bus into and then across system memory before this data becomes available to an application. Because of this the media layer should be implemented as close to the incoming data as possible. For embedded systems it is ideal if a Frame is the first location in system memory the received data occupies after being read out of peripheral memory. For higher-level systems it is ideal if a Frame is the first location in user-space the data occupies after being received from a kernel.
As demonstrated by the above diagram, careful configuration of hardware filters and proper elision of unsupported data will minimize the amount of CPU used by libuavcan to copy data through system memory.
Constructor & Destructor Documentation
Frame() [1/3]
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::Frame (const Frame< MTUBytesParam, FlagBitsCompareMask > & rhs) inline
Copy constructor for frames.
Parameters
rhs The frame to copy from.
Frame() [2/3]
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::Frame (std::uint32_t can_id, const std::uint8_t * can_data, FrameDLC in_dlc, libuavcan::time::Monotonic can_timestamp) inline
Constructs a new Frame object with timestamp that copies data into this instance.
Parameters
can_id The 29-bit CAN id.
can_data The data to copy into this instance.
in_dlc The data length code for the can_data.
can_timestamp A monotonic timestamp that should be as close to the time the start-of-frame was received (for rx frames) or put-on-bus (for tx frames) as possible.
Frame() [3/3]
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::Frame (std::uint32_t can_id, const std::uint8_t * can_data, FrameDLC in_dlc) inline
Constructs a new Frame object that copies data into this instance.
Parameters
can_id The 29-bit CAN id.
can_data The data to copy into this instance.
in_dlc The data length code for the can_data.
Member Function Documentation
dlcToLength()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> static std::uint_fast8_t libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::dlcToLength (FrameDLC dlc) inline static
Converts a Data Length Code into a frame length.
Parameters
dlc The DLC to convert.
Returns
The maximum number of bytes the frame can occupy for the given DLC.
Lookup table to map a DLC value to the maximum data payload length supported for the DLC.
getDataLength()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> std::uint_fast8_t libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::getDataLength () const inline
Get length of the frame data in bytes.
Returns
std::uint_fast8_t The number of bytes this Frame object contains.
Referenced by libuavcan::example::SocketCANInterface::write().
getDLC()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> FrameDLC libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::getDLC () const inline
Get the Data Length Code set for this instance.
Returns
The DLC set for this instance.
Referenced by libuavcan::example::SocketCANInterface::write().
lengthToDlc()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> static FrameDLC libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::lengthToDlc (std::uint_fast8_t length) inline static
Converts a given frame length value into a Data Length Code.
Parameters
length The data length value to convert.
Returns
Returns the appropriate DLC value but saturates to the DLC for the MTUBytesParam parameter.
Lookup table to map a CAN frame length to a DLC value that will accommodate the frame.
operator!=()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> bool libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator!= (const Frame< MTUBytesParam, FlagBitsCompareMask > & rhs) const inline
Logical inverse of libuavcan::media::CAN::Frame::operator==(const libuavcan::media::CAN::Frame&) const
Returns
true if libuavcan::media::CAN::Frame::operator==(const libuavcan::media::CAN::Frame&) const returns false.
operator<()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> bool libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator< (const Frame< MTUBytesParam, FlagBitsCompareMask > & other) const inline
CAN Frame comparisons compare the priority of the frames not the values.
See also
Frame::priorityHigherThan for more details on CAN bus arbitration.
operator=()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> Frame& libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator= (const Frame< MTUBytesParam, FlagBitsCompareMask > & rhs) inline
Assignment operator. This will copy all the data from rhs into this instance.
Parameters
rhs The frame to copy data from.
References libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::data, libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::id, and libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::timestamp.
operator==()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> bool libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator== (const Frame< MTUBytesParam, FlagBitsCompareMask > & rhs) const inline
Compares equality for the CAN Frame identifier, DLC (Data Length Code), and data.
Returns
true if both identifiers masked by MaskIdWithFlags are equal, both DLCs are equal, and the data in both frames are equal.
References libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::data, and libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::id.
operator>()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> bool libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator> (const Frame< MTUBytesParam, FlagBitsCompareMask > & other) const inline
CAN Frame comparisons compare the priority of the frames not the values.
See also
Frame::priorityHigherThan for more details on CAN bus arbitration.
priorityHigherThan()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> bool libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::priorityHigherThan (const Frame< MTUBytesParam, FlagBitsCompareMask > & rhs) const inline
Simple comparison of CAN identifiers. Since it is illegal to populate a Frame with any message type not supported by UAVCAN (e.g. error frames or frames with 11-bit identifiers) this method does a trivial comparison between two can identifiers.
Parameters
rhs A frame to compare with.
Returns
true if the rhs identifier is < this frame's id.
Note
See Marco Di Natale - "Understanding and using the Controller Area Network" for information on how CAN message identifiers are used in CAN arbitration.
References libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::id.
Referenced by libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::priorityLowerThan().
priorityLowerThan()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> bool libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::priorityLowerThan (const Frame< MTUBytesParam, FlagBitsCompareMask > & rhs) const inline
Simple comparison of CAN identifiers.
See also
Frame::priorityHigherThan for more details.
Parameters
rhs A frame to compare with.
Returns
true if the rhs identifier is > this frame's id.
References libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::priorityHigherThan().
setDataLength()
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> void libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::setDataLength (std::uint_fast8_t data_length) inline
Set the Data Length for this Frame. This value can be quantized for some lengths as only the Data Length Code is stored internally. So setDataLength(some_value) may not be equal to getDataLength(). after it is called.
Parameters
data_length The data length in bytes.
Field Documentation
data
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> std::uint8_t libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::data[MTUBytesParam]
System memory buffer of a CAN frame.
Referenced by libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator=(), libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator==(), and libuavcan::example::SocketCANInterface::write().
id
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> std::uint32_t libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::id
The 29-bit CAN identifier. The upper three bits is ignored by default but applications can use these bits either opaquely or by enabling in frame comparisons them using the FlagBitsCompareMask template parameter.
// Enable comparison of the 30th bit in the identifier.
CAN::Frame<CAN::TypeFD::MaxFrameSizeBytes,0x01> frame;
// Use the 30th bit.
frame.id = (can_id | (MY_FLAG << 29);
Referenced by libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator=(), libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator==(), libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::priorityHigherThan(), and libuavcan::example::SocketCANInterface::write().
MaskExtID
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> constexpr std::uint32_t libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::MaskExtID = 0x1FFFFFFFU static
29-bit mask for extended frame identifiers.
MaskIdWithFlags
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> constexpr std::uint32_t libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::MaskIdWithFlags static
Initial value:
=
        MaskExtID | (static_cast<std::uint32_t>(FlagBitsCompareMask) << 29)
The mask to use when comparing two Frame::id fields.
MTUBytes
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> constexpr std::uint16_t libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::MTUBytes = MTUBytesParam static
The maximum number of bytes this frame can hold. This value also effects the largest DLC the instance will report and the largest DLC the instance will accept.
timestamp
template<std::uint16_t MTUBytesParam, std::uint8_t FlagBitsCompareMask = 0x00> libuavcan::time::Monotonic libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::timestamp
A monotonic timestamp. Libuavcan operates optimally when this value is a hardware supplied timestamp recorded at the start-of-frame.
Referenced by libuavcan::media::CAN::Frame< MTUBytesParam, FlagBitsCompareMask >::operator=().
The documentation for this struct was generated from the following file:
/repo/libuavcan/include/libuavcan/media/can.hpp
UAVCAN Copyright (C) 2014-1029 Pavel Kirienko Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved This documentation is provided under the MIT licence as part of the libuavcan project.