steps:
  - label: ':hammer: native build and :mag: test'
    id: native-gcc-build-and-test
    command: "./ci/native-gcc-build-and-test.sh"
    artifact_paths: 
      - "build_ci_native_gcc/libuavcan"
      - "build_ci_native_gcc/docs/**/*"
    plugins:
      - docker#v3.1.0:
          workdir: /repo
          image: "uavcan/libuavcan:latest"
    env:
      VERBOSE: 1
    agents:
      queue: 'default'
    timeout_in_minutes: 15
  - label: ':hammer: native build using clang'
    id: native-clang-build
    command: "./ci/native-clang-build.sh"
    plugins:
      - docker#v3.1.0:
          workdir: /repo
          image: "uavcan/libuavcan:latest"
    env:
      VERBOSE: 1
    agents:
      queue: 'default'
    timeout_in_minutes: 15
  - label: ':hammer: s32k build'
    id: ontarget-s32k-build
    command: "./ci/ontarget-s32k-build.sh"
    artifact_paths: 
      - "build_ci_ontarget_s32k/**/*.log"
      - "build_ci_ontarget_s32k/**/*.elf"
      - "build_ci_ontarget_s32k/**/*.hex"
      - "build_ci_ontarget_s32k/**/*.bin"
      - "build_ci_ontarget_s32k/**/*.jlink"
    plugins:
      - docker#v3.1.0:
          workdir: /repo
          image: "uavcan/libuavcan:latest"
    env:
      VERBOSE: 1
    agents:
      queue: 'default'
    timeout_in_minutes: 15
  - wait
  - label: ":mag: ontarget testing"
    command: "./ci/ontarget-s32k-test.sh"
    agents:
      queue: "ontarget-s32k"
