#
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Toolchain for using clang on what-ever-platform-this-is (aka "native").
# CMake and/or Ubuntu defaults to gcc.
#
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)

# Signal to unit tests that the coverage data will be generated by
# clang so they should try to use llvm-cov if it's available. 
# Things are weird between gcov and llvm-cov right now but this 
# seems to work in our Ubuntu 18 Docker container, so...?
set(LIBUAVCAN_USE_LLVM_COV ON)
