name: "libcyphal_test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verification:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/opencyphal/toolshed:ts22.4.3
      options: --forcePull=false
    strategy:
      matrix:
        flavor: [Release, Debug]
        toolchain: [gcc, clang]
    steps:
    - uses: actions/checkout@v3
    - name: Cache ext modules
      id: libcyphal-ext
      uses: actions/cache@v3
      env:
        cache-name: libcyphal-ext-cache
      with:
        path: external
        key: ${{ runner.os }}-${{ hashFiles('cmake/modules/*.cmake') }}
    - name: release
      run: >
        ./build-tools/bin/verify.py
        --verbose
        --asserts
        --online
        --cpp-standard 14
        --build-flavor ${{ matrix.flavor }}
        --toolchain ${{ matrix.toolchain }}
        release
  docs:
    runs-on: ubuntu-latest
    container: ghcr.io/opencyphal/toolshed:ts22.4.3
    steps:
    - uses: actions/checkout@v3
    - name: Cache ext modules
      id: libcyphal-ext
      uses: actions/cache@v3
      env:
        cache-name: libcyphal-ext-cache
      with:
        path: external
        key: ${{ runner.os }}-${{ hashFiles('cmake/modules/*.cmake') }}
    - name: doc-gen
      run: >
        ./build-tools/bin/verify.py
        --verbose
        --asserts
        --online
        --cpp-standard 14
        --build-flavor Debug
        build-docs
    - name: Setup Pages
      if: ${{ github.event_name != 'pull_request' && !github.event.act }}
      uses: actions/configure-pages@v3
    - name: Upload docs
      if: ${{ github.event_name != 'pull_request' && !github.event.act }}
      uses: actions/upload-pages-artifact@v1
      with:
        path: "build/docs/html/"
    - name: upload-pr-docs
      if: ${{ github.event_name == 'pull_request' && !github.event.act }}
      uses: actions/upload-artifact@v3
      with:
        name: pr-docs
        path: "build/docs/html/"
        if-no-files-found: error

