name: verification CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  language-verification-cpp-14:
    runs-on: ubuntu-latest
    container: uavcan/c_cpp:ubuntu-20.04
    strategy:
      matrix:
        build_type: [Debug]
        target: [native]
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v3
      - run: test/ci/verify.py -v
                          --target ${{matrix.target}}
                          --build-type ${{ matrix.build_type }}
                          --toolchain-family ${{ matrix.compiler }}
                          --omit-style-check-from-all
                          configure
      - run: test/ci/verify.py -v
                          --target ${{matrix.target}}
                          --build-type ${{ matrix.build_type }}
                          --toolchain-family ${{ matrix.compiler }}
                          build
      - run: test/ci/verify.py -v
                          --target ${{matrix.target}}
                          --build-type ${{ matrix.build_type }}
                          --toolchain-family ${{ matrix.compiler }}
                          compile-test
      - run: test/ci/verify.py -v
                          --target ${{matrix.target}}
                          --build-type ${{ matrix.build_type }}
                          --toolchain-family ${{ matrix.compiler }}
                          test
                          test_all
